platform :ios, "7.0"
pod "CXPhotoBrowser"
pod "JSMessagesViewController"
pod "UIColor-HexString"
pod "BZGFormViewController"
pod "ECSlidingViewController"
pod "EGOCache"
pod "SVProgressHUD"
pod "PopoverView"